# Generated by Django 2.0.7 on 2018-07-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocolos', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolos.Protocols'),
        ),
    ]
