# Generated by Django 2.0.7 on 2018-07-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_history_protocol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regionals',
            table='regionals',
        ),
    ]
