# Generated by Django 2.0.7 on 2018-07-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20180705_0651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail',
            table='loss_detail',
        ),
        migrations.AlterModelTable(
            name='insurancetype',
            table='insurance_types',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='reasonsforloss',
            table='loss_reasons',
        ),
    ]
