# Generated by Django 2.0.7 on 2018-07-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20180705_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='protocol',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
