# Generated by Django 2.0.7 on 2018-07-19 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20180718_0641'),
        ('pipeline', '0005_auto_20180706_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalsAccessedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'regionals_accessed_by',
            },
        ),
        migrations.CreateModel(
            name='SubsidiariesAccessedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'subsidiaries_accessed_by',
            },
        ),
        migrations.AddField(
            model_name='commercials',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='congeners',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancetype',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionals',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidiaries',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidiariesaccessedby',
            name='subsidiaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Regionals'),
        ),
        migrations.AddField(
            model_name='subsidiariesaccessedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='regionalsaccessedby',
            name='regionals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Regionals'),
        ),
        migrations.AddField(
            model_name='regionalsaccessedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
