# Generated by Django 2.0.7 on 2018-07-25 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_auto_20180719_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiariesaccessedby',
            name='subsidiaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Subsidiaries'),
        ),
    ]
