# Generated by Django 2.0.7 on 2018-08-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipeline', '0008_auto_20180725_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('revenues', models.BigIntegerField()),
                ('foundation_date', models.DateField()),
                ('employees', models.BigIntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=240)),
                ('cellphone_number', models.IntegerField()),
                ('birthday', models.DateField()),
                ('occupation', models.CharField(max_length=300)),
                ('hobby', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Clients')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='loss_comentary',
            new_name='loss_commentary',
        ),
    ]
