# Generated by Django 2.0.7 on 2018-07-18 05:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='address_complement',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='companies',
            name='address_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='companies',
            name='cellphone',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='companies',
            name='county',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='companies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='documentId',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='companies',
            name='endpoint',
            field=models.CharField(default=None, max_length=280),
        ),
        migrations.AddField(
            model_name='companies',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='phone',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='companies',
            name='postal_code',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='companies',
            name='street',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='companies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.Companies'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextended',
            name='phone',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
