# Generated by Django 2.0.7 on 2018-07-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('broker', models.CharField(max_length=250)),
                ('first_quotation', models.BooleanField()),
                ('client', models.CharField(max_length=250)),
                ('prize', models.IntegerField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('receipt', models.DateField()),
                ('maturity', models.DateField()),
                ('closure', models.DateField()),
                ('subscriber', models.CharField(max_length=250)),
                ('loss_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('loss_detail', models.CharField(blank=True, max_length=400, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Commercials')),
                ('congener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.Congeners')),
                ('expectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Expectations')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.InsuranceType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Products')),
                ('reason_for_loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.ReasonsForLoss')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Regionals')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Status')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Subsidiaries')),
            ],
            options={
                'db_table': 'protocols',
            },
        ),
    ]
