# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expectativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectativa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoPerda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretor', models.CharField(max_length=250)),
                ('primeira_cotacao', models.BooleanField()),
                ('cliente', models.CharField(max_length=250)),
                ('premio', models.IntegerField()),
                ('ultima_alteracao', models.DateField(auto_now=True)),
                ('data_recebimento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('previsao_fechamento', models.DateField()),
                ('comentario_perda', models.CharField(max_length=250)),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Comercial')),
                ('expectativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Expectativa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Filial')),
                ('motivo_perda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MotivoPerda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipodeSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='protocolos',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Regional'),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='tipo_de_seguro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TipodeSeguro'),
        ),
    ]
