# Generated by Django 2.0 on 2018-03-28 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolos',
            old_name='data_recebimento',
            new_name='fechamento',
        ),
        migrations.RenameField(
            model_name='protocolos',
            old_name='data_vencimento',
            new_name='recebimento',
        ),
        migrations.RenameField(
            model_name='protocolos',
            old_name='previsao_fechamento',
            new_name='vencimento',
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_1',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_10',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_2',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_3',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_4',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_5',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_6',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_7',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_8',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='protocolos',
            name='historico_9',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='protocolos',
            name='comentario_perda',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='protocolos',
            name='motivo_perda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.MotivoPerda'),
        ),
    ]
