# Generated by Django 2.0 on 2018-03-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180328_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolos',
            name='subscritor',
            field=models.CharField(default='nada', max_length=250),
            preserve_default=False,
        ),
    ]
