# Generated by Django 2.0.6 on 2018-06-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180615_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolos',
            name='updated_at',
        ),
    ]
